id: hsr
name: 崩坏：星穹铁道
gear_name: 遗器 / 位面饰品
random_position_actions: false
sets:
- 叩问天工的名冶
- 星如我见的领航员
- 应天涉远的卜者
- 闪耀功勋的魔法少女
- 再创天地的救世主
- 自匿星芒的隐士
- 恶海逐波的船长
- 烈阳惊雷的女武神
- 凯歌祝捷的英豪
- 哀歌覆国的诗人
- 识海迷坠的学者
- 重循苦旅的司铎
- 荡除蠹灾的铁骑
- 风举云飞的勇烈
- 机心戏梦的钟表匠
- 死水深潜的先驱
- 幽锁深牢的系囚
- 毁烬焚骨的大公
- 宝命长存的莳者
- 骇域漫游的信使
- 云无留迹的过客
- 净庭教宗的圣骑士
- 密林卧雪的猎人
- 戍卫风雪的铁卫
- 晨昏交界的翔鹰
- 流星追迹的怪盗
- 激奏雷电的乐队
- 熔岩锻铸的火匠
- 盗匪荒漠的废土客
- 繁星璀璨的天才
- 街头出身的拳王
- 野穗伴行的快枪手
- 坠星启航地
- 寰宇生研院
- 千星荟萃之城
- 零号关卡朋克洛德
- 天国@直播间
- 永恒之地翁法罗斯
- 妖精织梦的乐园
- 沉欢醉饮的海隅
- 渊思寂虑的巨树
- 谧宁拾骨地
- 奇想蕉乐园
- 沉陆海域露莎卡
- 劫火莲灯铸炼宫
- 奔狼的都蓝王朝
- 出云显世与高天神国
- 无主荒星茨冈尼亚
- 梦想之地匹诺康尼
- 苍穹战线格拉默
- 折断的龙骨
- 繁星竞技场
- 不老者的仙舟
- 停转的萨尔索图
- 太空封印站
- 星体差分机
- 泛银河商业公司
- 生命的翁瓦克
- 盗贼公国塔利亚
- 筑城者的贝洛伯格
set_effects:
  叩问天工的名冶:
    two_piece: 生命上限提高12%。
    four_piece: 装备者对防御力降低状态的敌方目标造成的暴击伤害提高28%。装备者对敌方目标施加防御力降低状态后，使我方全体获得【助燃】，持续2回合，该效果无法叠加，持有【助燃】的我方目标造成的伤害提高15%。该效果在装备者施放攻击后可再次触发。
  星如我见的领航员:
    two_piece: 攻击力提高12%。
    four_piece: 装备者进入战斗时/施放战技时，使战技和终结技造成的伤害提高18%，最多叠加3层，装备者回合开始时/施放终结技后，移除1层该效果。
  应天涉远的卜者:
    two_piece: 速度提高6%。
    four_piece: 进入战斗前，若装备者的速度大于等于120/160，使装备者的暴击率提高10%/18%。装备者每场战斗首次施放欢愉技时，使我方全体欢愉度提高10%，该效果无法叠加。
  闪耀功勋的魔法少女:
    two_piece: 暴击伤害提高16%。
    four_piece: 装备者及其忆灵造成的欢愉伤害无视目标10%的防御力，我方每累计获得5点笑点，造成的欢愉伤害额外无视目标1%的防御力，最多叠加10层。
  再创天地的救世主:
    two_piece: 暴击率提高8%。
    four_piece: 装备者施放普攻或战技后，若装备者的忆灵在场，使装备者及其忆灵生命上限提高24%，我方全体造成的伤害提高15%，持续至装备者下次施放普攻或战技后。
  自匿星芒的隐士:
    two_piece: 提供的护盾量提高10%。
    four_piece: 使装备者提供的护盾量提高12%，我方目标持有装备者提供的护盾时，暴击伤害提高15%。
  恶海逐波的船长:
    two_piece: 暴击伤害提高16%。
    four_piece: 装备者成为其他我方目标的技能目标时，获得1层【助力】，最多叠加2层。施放终结技时，若持有2层【助力】，消耗所有【助力】，使装备者攻击力提高48%，持续1回合。
  烈阳惊雷的女武神:
    two_piece: 速度提高6%。
    four_piece: 当装备者及其忆灵为装备者及其忆灵以外的我方目标提供治疗后，使装备者获得【甘霖】，每回合最多触发1次，持续2回合。装备者持有【甘霖】时，速度提高6%，我方全体暴击伤害提高15%，该效果无法叠加。
  凯歌祝捷的英豪:
    two_piece: 攻击力提高12%。
    four_piece: 装备者的忆灵在场时，装备者的速度提高6%，装备者的忆灵攻击时，装备者和忆灵的暴击伤害提高30%，持续2回合。
  哀歌覆国的诗人:
    two_piece: 量子属性伤害提高10%。
    four_piece: 使装备者的速度降低8%。进入战斗前，若装备者的速度小于110/95，使装备者的暴击率提高20%/32%。该效果同时对装备者的忆灵生效。
  识海迷坠的学者:
    two_piece: 暴击率提高8%。
    four_piece: 战技和终结技造成的伤害提高20%，施放终结技后，下一次施放战技时造成的伤害额外提高25%。
  重循苦旅的司铎:
    two_piece: 速度提高6%。
    four_piece: 对我方单体目标施放战技或终结技时，使技能目标的暴击伤害提高18%，持续2回合，该效果最多叠加2次。
  荡除蠹灾的铁骑:
    two_piece: 击破特攻提高16%。
    four_piece: 当装备者的击破特攻大于等于150%时，对目标造成的击破伤害无视目标10%防御力。当装备者的击破特攻大于等于250%时，对目标造成的超击破伤害额外无视其15%防御力。
  风举云飞的勇烈:
    two_piece: 攻击力提高12%。
    four_piece: 使装备者暴击率提高6%，装备者施放追加攻击时，使终结技造成的伤害提高36%，该效果持续1回合。
  机心戏梦的钟表匠:
    two_piece: 击破特攻提高16%。
    four_piece: 当装备者对我方目标施放终结技时，我方全体击破特攻提高30%，持续2回合，该效果无法叠加。
  死水深潜的先驱:
    two_piece: 对受负面状态影响的敌人造成的伤害提高12%。
    four_piece: 暴击率提高4%，装备者对陷入不少于2/3个负面效果的敌方目标造成的暴击伤害提高8%/12%。装备者对敌方目标施加负面效果后，上述效果提高100%，持续1回合。
  幽锁深牢的系囚:
    two_piece: 攻击力提高12%。
    four_piece: 敌方目标每承受1个持续伤害效果，装备者对其造成伤害时就无视其6%的防御力，最多计入3个持续伤害效果。
  毁烬焚骨的大公:
    two_piece: 追加攻击造成的伤害提高20%。
    four_piece: 装备者对敌方目标施放追加攻击时，根据追加攻击造成伤害的次数，每次造成伤害时使装备者的攻击力提高6%，最多叠加8次，持续3回合。该效果在装备者下一次施放追加攻击时移除。
  宝命长存的莳者:
    two_piece: 生命上限提高12%。
    four_piece: 当装备者受到攻击或被我方目标消耗生命值后，暴击率提高8%，持续2回合，该效果最多叠加2层。
  骇域漫游的信使:
    two_piece: 速度提高6%。
    four_piece: 当装备者对我方目标施放终结技时，我方全体速度提高12%，持续1回合，该效果无法叠加。
  云无留迹的过客:
    two_piece: 治疗量提高10%。
    four_piece: 在战斗开始时，立即为我方恢复1个战技点。
  净庭教宗的圣骑士:
    two_piece: 防御力提高15%。
    four_piece: 使装备者提供的护盾量提高20%。
  密林卧雪的猎人:
    two_piece: 冰属性伤害提高10%。
    four_piece: 当装备者施放终结技时，暴击伤害提高25%，持续2回合。
  戍卫风雪的铁卫:
    two_piece: 受到伤害降低8%。
    four_piece: 回合开始时，如果装备者当前生命值百分比小于等于50%，则回复等同于自身生命上限8%的生命值，并恢复5点能量。
  晨昏交界的翔鹰:
    two_piece: 风属性伤害提高10%。
    four_piece: 当装备者施放终结技后，使其行动提前25%。
  流星追迹的怪盗:
    two_piece: 击破特攻提高16%。
    four_piece: 使装备者的击破特攻提高16%。当装备者击破敌方目标弱点后，恢复3点能量。
  激奏雷电的乐队:
    two_piece: 雷属性伤害提高10%。
    four_piece: 当装备者施放战技时，使装备者的攻击力提高20%，持续1回合。
  熔岩锻铸的火匠:
    two_piece: 火属性伤害提高10%。
    four_piece: 使装备者战技造成的伤害提高12%，并使施放终结技后的下一次攻击造成的火属性伤害提高12%。
  盗匪荒漠的废土客:
    two_piece: 虚数属性伤害提高10%。
    four_piece: 装备者对陷入负面效果的敌方目标造成伤害时暴击率提高10%，对陷入禁锢状态的敌方目标造成伤害时暴击伤害提高20%。
  繁星璀璨的天才:
    two_piece: 量子属性伤害提高10%。
    four_piece: 当装备者对敌方目标造成伤害时，无视其10%的防御力。若目标拥有量子属性弱点，额外无视其10%的防御力。
  街头出身的拳王:
    two_piece: 物理属性伤害提高10%。
    four_piece: 当装备者施放攻击或受到攻击后，其在本场战斗中攻击力提高5%，最多叠加5层。
  野穗伴行的快枪手:
    two_piece: 攻击力提高12%。
    four_piece: 使装备者的速度提高6%，普攻造成的伤害提高10%。
  坠星启航地:
    two_piece: 资料源暂未填写2件套效果。
    four_piece: 位面饰品通常只启用2件套效果。
  寰宇生研院:
    two_piece: 资料源暂未填写2件套效果。
    four_piece: 位面饰品通常只启用2件套效果。
  千星荟萃之城:
    two_piece: 装备者施放追加攻击时，攻击力提高24%，持续2回合。当敌方目标被消灭时，我方全体在本场战斗中暴击伤害提高12%，该效果无法叠加。
    four_piece: 位面饰品通常只启用2件套效果。
  零号关卡朋克洛德:
    two_piece: 使装备者的欢愉度提高8%。战斗中欢愉度首次达到40%/80%时，使装备者暴击伤害提高20%/32%。
    four_piece: 位面饰品通常只启用2件套效果。
  天国@直播间:
    two_piece: 使装备者的暴击伤害提高16%。若在同一回合内消耗大于等于3点战技点，额外使装备者暴击伤害提高32%，持续3回合。
    four_piece: 位面饰品通常只启用2件套效果。
  永恒之地翁法罗斯:
    two_piece: 使装备者的暴击率提高8%。装备者的忆灵在场时，我方全体速度提高8%，该效果无法叠加。
    four_piece: 位面饰品通常只启用2件套效果。
  妖精织梦的乐园:
    two_piece: 队伍中当前在场的我方目标数量不等于4时，每多/少1名我方目标，使装备者及其忆灵造成的伤害提高9%/12%，最多叠加4/3层。
    four_piece: 位面饰品通常只启用2件套效果。
  沉欢醉饮的海隅:
    two_piece: 使装备者的攻击力提高12%。当装备者的攻击力大于等于2400/3600时，使造成的持续伤害额外提高12%/24%。
    four_piece: 位面饰品通常只启用2件套效果。
  渊思寂虑的巨树:
    two_piece: 使装备者的速度提高6%。当装备者的速度大于等于135/180时，使装备者及其忆灵的治疗量提高12%/20%。
    four_piece: 位面饰品通常只启用2件套效果。
  谧宁拾骨地:
    two_piece: 使装备者的生命上限提高12%。当装备者的生命上限大于等于5000点时，使装备者及其忆灵的暴击伤害提高28%。
    four_piece: 位面饰品通常只启用2件套效果。
  奇想蕉乐园:
    two_piece: 使装备者的暴击伤害提高16.0%，当存在装备者召唤的目标时，暴击伤害额外提高32.0%。
    four_piece: 位面饰品通常只启用2件套效果。
  沉陆海域露莎卡:
    two_piece: 使装备者的能量恢复效率提高5.0%，如果装备者不是编队中的第一位角色，使编队中的第一位角色攻击力提高12.0%。
    four_piece: 位面饰品通常只启用2件套效果。
  劫火莲灯铸炼宫:
    two_piece: 使装备者的速度提高6%。当装备者击中拥有火属性弱点的敌方目标时，击破特攻提高40%，持续1回合。
    four_piece: 位面饰品通常只启用2件套效果。
  奔狼的都蓝王朝:
    two_piece: 我方角色施放追加攻击时，装备者获得一层【功勋】，最多叠加5层，每层【功勋】使装备者追加攻击造成的伤害提高5%，叠满5层时，额外使装备者的暴击伤害提高25%。
    four_piece: 位面饰品通常只启用2件套效果。
  出云显世与高天神国:
    two_piece: 使装备者的攻击力提高12%。进入战斗时，若至少存在一名与装备者命途相同的队友，装备者的暴击率提高12%。
    four_piece: 位面饰品通常只启用2件套效果。
  无主荒星茨冈尼亚:
    two_piece: 使装备者的暴击率提高4%。当敌方目标被消灭时，装备者暴击伤害提高4%，最多叠加10层。
    four_piece: 位面饰品通常只启用2件套效果。
  梦想之地匹诺康尼:
    two_piece: 使装备者的能量恢复效率提高5%。使队伍中与装备者属性相同的我方其他角色造成的伤害提高10%。
    four_piece: 位面饰品通常只启用2件套效果。
  苍穹战线格拉默:
    two_piece: 使装备者的攻击力提高12%。当装备者的速度大于等于135/160时，使装备者造成的伤害提高12%/18%。
    four_piece: 位面饰品通常只启用2件套效果。
  折断的龙骨:
    two_piece: 使装备者的效果抵抗提高10%。当装备者的效果抵抗大于等于30%时，我方全体暴击伤害提高10%。
    four_piece: 位面饰品通常只启用2件套效果。
  繁星竞技场:
    two_piece: 使装备者的暴击率提高8%。当装备者的当前暴击率大于等于70%时，普攻和战技造成的伤害提高20%。
    four_piece: 位面饰品通常只启用2件套效果。
  不老者的仙舟:
    two_piece: 使装备者的生命上限提高12%。当装备者的速度大于等于120时，我方全体攻击力提高8%。
    four_piece: 位面饰品通常只启用2件套效果。
  停转的萨尔索图:
    two_piece: 使装备者的暴击率提高8%。当装备者当前暴击率大于等于50%时，终结技和追加攻击造成的伤害提高15%。
    four_piece: 位面饰品通常只启用2件套效果。
  太空封印站:
    two_piece: 使装备者的攻击力提高12%。当装备者的速度大于等于120时，攻击力额外提高12%。
    four_piece: 位面饰品通常只启用2件套效果。
  星体差分机:
    two_piece: 使装备者的暴击伤害提高16%。当装备者的暴击伤害大于等于120%时，进入战斗后装备者的暴击率提高60%，持续到施放首次攻击后结束。
    four_piece: 位面饰品通常只启用2件套效果。
  泛银河商业公司:
    two_piece: 使装备者的效果命中提高10%，同时提高装备者等同于当前效果命中25%的攻击力，最多提高25%。
    four_piece: 位面饰品通常只启用2件套效果。
  生命的翁瓦克:
    two_piece: 使装备者的能量恢复效率提高5%。当装备者的速度大于等于120时，进入战斗时立刻使行动提前40%。
    four_piece: 位面饰品通常只启用2件套效果。
  盗贼公国塔利亚:
    two_piece: 使装备者的击破特攻提高16%。当装备者的速度大于等于145时，击破特攻额外提高20%。
    four_piece: 位面饰品通常只启用2件套效果。
  筑城者的贝洛伯格:
    two_piece: 使装备者的防御力提高15%。当装备者的效果命中大于等于50%时，防御力额外提高15%。
    four_piece: 位面饰品通常只启用2件套效果。
position_set_names:
  head:
  - 叩问天工的名冶
  - 星如我见的领航员
  - 应天涉远的卜者
  - 闪耀功勋的魔法少女
  - 再创天地的救世主
  - 自匿星芒的隐士
  - 恶海逐波的船长
  - 烈阳惊雷的女武神
  - 凯歌祝捷的英豪
  - 哀歌覆国的诗人
  - 识海迷坠的学者
  - 重循苦旅的司铎
  - 荡除蠹灾的铁骑
  - 风举云飞的勇烈
  - 机心戏梦的钟表匠
  - 死水深潜的先驱
  - 幽锁深牢的系囚
  - 毁烬焚骨的大公
  - 宝命长存的莳者
  - 骇域漫游的信使
  - 云无留迹的过客
  - 净庭教宗的圣骑士
  - 密林卧雪的猎人
  - 戍卫风雪的铁卫
  - 晨昏交界的翔鹰
  - 流星追迹的怪盗
  - 激奏雷电的乐队
  - 熔岩锻铸的火匠
  - 盗匪荒漠的废土客
  - 繁星璀璨的天才
  - 街头出身的拳王
  - 野穗伴行的快枪手
  hands:
  - 叩问天工的名冶
  - 星如我见的领航员
  - 应天涉远的卜者
  - 闪耀功勋的魔法少女
  - 再创天地的救世主
  - 自匿星芒的隐士
  - 恶海逐波的船长
  - 烈阳惊雷的女武神
  - 凯歌祝捷的英豪
  - 哀歌覆国的诗人
  - 识海迷坠的学者
  - 重循苦旅的司铎
  - 荡除蠹灾的铁骑
  - 风举云飞的勇烈
  - 机心戏梦的钟表匠
  - 死水深潜的先驱
  - 幽锁深牢的系囚
  - 毁烬焚骨的大公
  - 宝命长存的莳者
  - 骇域漫游的信使
  - 云无留迹的过客
  - 净庭教宗的圣骑士
  - 密林卧雪的猎人
  - 戍卫风雪的铁卫
  - 晨昏交界的翔鹰
  - 流星追迹的怪盗
  - 激奏雷电的乐队
  - 熔岩锻铸的火匠
  - 盗匪荒漠的废土客
  - 繁星璀璨的天才
  - 街头出身的拳王
  - 野穗伴行的快枪手
  body:
  - 叩问天工的名冶
  - 星如我见的领航员
  - 应天涉远的卜者
  - 闪耀功勋的魔法少女
  - 再创天地的救世主
  - 自匿星芒的隐士
  - 恶海逐波的船长
  - 烈阳惊雷的女武神
  - 凯歌祝捷的英豪
  - 哀歌覆国的诗人
  - 识海迷坠的学者
  - 重循苦旅的司铎
  - 荡除蠹灾的铁骑
  - 风举云飞的勇烈
  - 机心戏梦的钟表匠
  - 死水深潜的先驱
  - 幽锁深牢的系囚
  - 毁烬焚骨的大公
  - 宝命长存的莳者
  - 骇域漫游的信使
  - 云无留迹的过客
  - 净庭教宗的圣骑士
  - 密林卧雪的猎人
  - 戍卫风雪的铁卫
  - 晨昏交界的翔鹰
  - 流星追迹的怪盗
  - 激奏雷电的乐队
  - 熔岩锻铸的火匠
  - 盗匪荒漠的废土客
  - 繁星璀璨的天才
  - 街头出身的拳王
  - 野穗伴行的快枪手
  feet:
  - 叩问天工的名冶
  - 星如我见的领航员
  - 应天涉远的卜者
  - 闪耀功勋的魔法少女
  - 再创天地的救世主
  - 自匿星芒的隐士
  - 恶海逐波的船长
  - 烈阳惊雷的女武神
  - 凯歌祝捷的英豪
  - 哀歌覆国的诗人
  - 识海迷坠的学者
  - 重循苦旅的司铎
  - 荡除蠹灾的铁骑
  - 风举云飞的勇烈
  - 机心戏梦的钟表匠
  - 死水深潜的先驱
  - 幽锁深牢的系囚
  - 毁烬焚骨的大公
  - 宝命长存的莳者
  - 骇域漫游的信使
  - 云无留迹的过客
  - 净庭教宗的圣骑士
  - 密林卧雪的猎人
  - 戍卫风雪的铁卫
  - 晨昏交界的翔鹰
  - 流星追迹的怪盗
  - 激奏雷电的乐队
  - 熔岩锻铸的火匠
  - 盗匪荒漠的废土客
  - 繁星璀璨的天才
  - 街头出身的拳王
  - 野穗伴行的快枪手
  sphere:
  - 坠星启航地
  - 寰宇生研院
  - 千星荟萃之城
  - 零号关卡朋克洛德
  - 天国@直播间
  - 永恒之地翁法罗斯
  - 妖精织梦的乐园
  - 沉欢醉饮的海隅
  - 渊思寂虑的巨树
  - 谧宁拾骨地
  - 奇想蕉乐园
  - 沉陆海域露莎卡
  - 劫火莲灯铸炼宫
  - 奔狼的都蓝王朝
  - 出云显世与高天神国
  - 无主荒星茨冈尼亚
  - 梦想之地匹诺康尼
  - 苍穹战线格拉默
  - 折断的龙骨
  - 繁星竞技场
  - 不老者的仙舟
  - 停转的萨尔索图
  - 太空封印站
  - 星体差分机
  - 泛银河商业公司
  - 生命的翁瓦克
  - 盗贼公国塔利亚
  - 筑城者的贝洛伯格
  rope:
  - 坠星启航地
  - 寰宇生研院
  - 千星荟萃之城
  - 零号关卡朋克洛德
  - 天国@直播间
  - 永恒之地翁法罗斯
  - 妖精织梦的乐园
  - 沉欢醉饮的海隅
  - 渊思寂虑的巨树
  - 谧宁拾骨地
  - 奇想蕉乐园
  - 沉陆海域露莎卡
  - 劫火莲灯铸炼宫
  - 奔狼的都蓝王朝
  - 出云显世与高天神国
  - 无主荒星茨冈尼亚
  - 梦想之地匹诺康尼
  - 苍穹战线格拉默
  - 折断的龙骨
  - 繁星竞技场
  - 不老者的仙舟
  - 停转的萨尔索图
  - 太空封印站
  - 星体差分机
  - 泛银河商业公司
  - 生命的翁瓦克
  - 盗贼公国塔利亚
  - 筑城者的贝洛伯格
board_layout:
- - head
  - hands
  - body
- - feet
  - sphere
  - rope
positions:
- id: head
  name: 头部
  main_stats:
  - 生命值
- id: hands
  name: 手部
  main_stats:
  - 攻击力
- id: body
  name: 躯干
  main_stats:
  - 暴击率
  - 暴击伤害
  - 治疗量加成
  - 效果命中
  - 生命值百分比
  - 攻击力百分比
  - 防御力百分比
- id: feet
  name: 脚部
  main_stats:
  - 速度
  - 生命值百分比
  - 攻击力百分比
  - 防御力百分比
- id: sphere
  name: 位面球
  main_stats:
  - 物理属性伤害
  - 火属性伤害
  - 冰属性伤害
  - 雷属性伤害
  - 风属性伤害
  - 量子属性伤害
  - 虚数属性伤害
  - 生命值百分比
  - 攻击力百分比
  - 防御力百分比
- id: rope
  name: 连结绳
  main_stats:
  - 能量恢复效率
  - 击破特攻
  - 生命值百分比
  - 攻击力百分比
  - 防御力百分比
sub_stats:
- 暴击率
- 暴击伤害
- 速度
- 效果命中
- 效果抵抗
- 击破特攻
- 攻击力
- 攻击力百分比
- 生命值
- 生命值百分比
- 防御力
- 防御力百分比
main_stat_probabilities:
  head:
    生命值: 1.0
  hands:
    攻击力: 1.0
  body:
    暴击率: 0.1
    暴击伤害: 0.1
    治疗量加成: 0.1
    效果命中: 0.1
    生命值百分比: 0.2
    攻击力百分比: 0.2
    防御力百分比: 0.2
  feet:
    速度: 0.12
    生命值百分比: 0.28
    攻击力百分比: 0.3
    防御力百分比: 0.3
  sphere:
    物理属性伤害: 0.09
    火属性伤害: 0.09
    冰属性伤害: 0.09
    雷属性伤害: 0.09
    风属性伤害: 0.09
    量子属性伤害: 0.09
    虚数属性伤害: 0.09
    生命值百分比: 0.12
    攻击力百分比: 0.13
    防御力百分比: 0.12
  rope:
    能量恢复效率: 0.0510204082
    击破特攻: 0.1632653061
    生命值百分比: 0.2653061224
    攻击力百分比: 0.2755102041
    防御力百分比: 0.2448979592
sub_stat_probabilities:
  暴击率: 6.0
  暴击伤害: 6.0
  速度: 4.0
  效果命中: 8.0
  效果抵抗: 8.0
  击破特攻: 8.0
  攻击力: 10.0
  攻击力百分比: 10.0
  生命值: 10.0
  生命值百分比: 10.0
  防御力: 10.0
  防御力百分比: 10.0
enhancement:
  max_level: 15
  step: 3
  initial_add_level: 3
